package br.com.senai.model;

// CLASSE ENUM
// ENUM É UMA CLASSE ESPECIAL QUE REPRESENTA UM CONJUNTO DE CONSTANTES IMUTÁVEIS
// AQUI, CADA FORMA DE PAGAMENTO SE REFERE A UM TIPO DE PAGAMENTO ACEITO PELO SISTEMA
public enum FormaPagamento {
    DINHEIRO,
    CARTAO
}