package br.com.senai.model;

// CLASSE ENUM
// ENUM É UMA CLASSE ESPECIAL QUE REPRESENTA UM CONJUNTO DE CONSTANTES IMUTÁVEIS
// AQUI, CADA PERFIL DE ACESSO SE REFERE A UM TIPO DE USUÁRIO DO SISTEMA, COM PERMISSÕES DIFERENTES
public enum Perfil {
    ADMIN,
    VENDEDOR
}